global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'trade_orchestrator'
    static_configs:
      - targets: ['trade_orchestrator:8000']
  - job_name: 'market_data'
    static_configs:
      - targets: ['market_data:8000']
  - job_name: 'router_parser'
    static_configs:
      - targets: ['router_parser:8000']
